//
// Created by yellowos on 02/02/2018.
//

#ifndef MOVING_CATCH_PARAMTERS_H
#define MOVING_CATCH_PARAMTERS_H

#define DEBUG_MODE 0
#define IMAGE_HIGH 1080
#define IMAGE_WIDTH 1920

#endif //MOVING_CATCH_PARAMTERS_H
